name: boosting-process
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attr=2.5.1
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - graphite2=1.3.14
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=7.3.0
  - icu=72.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libclang=16.0.5
  - libclang13=16.0.5
  - libcups=2.3.3
  - libdeflate=1.18
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.2
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.76.3
  - libgomp=13.1.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libllvm14=14.0.6
  - libllvm16=16.0.5
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvmlite=0.40.0
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpg123=1.31.3
  - munkres=1.1.4
  - mypy=0.981
  - mypy_extensions=0.4.3
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.89.1
  - numba=0.57.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=2.5.2
  - ply=3.11
  - polars=0.18.2
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.7
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=67.8.0
  - sip=6.7.9
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.5
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
